export const siteContent = {
  brand: {
    name: "Miriã Cotrim",
    tagline: "Bridal Beauty",
    version: "Copyright 2026 - Orlando, USA",
  },
  professional: {
    bio: "Miriã believes beauty should feel personal, effortless and unforgettable. Her work combines technique, attention to detail and a personalized approach to create looks designed for each client's style, personality and special moment.",
    bioApprovalPending: true,
  },
  contact: {
    WHATSAPP_NUMBER: "16893170689",
    email: "",
    location: "Orlando and Miami, Florida",
  },
  socialMedia: {
    Instagram: "https://www.instagram.com/miriacotrim/",
    Facebook: "",
    TikTok: "",
    Pinterest: "",
  },
  navigation: [
    ["Home", "/"],
    ["About", "/about"],
    ["Services", "/services"],
    ["Bridal", "/bridal"],
    ["Portfolio", "/portfolio"],
    ["Book", "/book"],
    ["Contact", "/contact"],
  ],
  services: [
    {
      name: "Bridal Beauty",
      sub: "Hair and makeup for your once-in-a-lifetime moment.",
      image: 27,
      href: "/bridal",
    },
    {
      name: "Special Events",
      sub: "Birthdays, celebrations, photoshoots and elevated event beauty.",
      image: 46,
      href: "/services#events",
    },
    {
      name: "Hair Services",
      sub: "Cuts, styling, treatments and transformations planned around you.",
      image: 35,
      href: "/services#hair",
    },
    {
      name: "Beauty Consultation",
      sub: "A personal conversation to choose the right look, timing and service.",
      image: 32,
      href: "/book",
    },
  ],
  bridalServices: [
    "Bridal Hair",
    "Bridal Makeup",
    "Bridal Trial",
    "Bridesmaids",
    "Mother of the Bride",
    "Mother of the Groom",
    "Wedding Party",
    "Special Event Styling",
    "On-location Beauty",
  ],
  booking: {
    services: [
      "Bridal Consultation",
      "Bridal Trial",
      "Hair + Makeup",
      "Makeup",
      "Hair Styling",
      "Haircut",
      "Hair Treatment",
      "Special Event Beauty",
    ],
    types: [
      "Bride",
      "Bridesmaid",
      "Mother of the Bride",
      "Wedding Guest",
      "Birthday",
      "Photoshoot",
      "Special Event",
      "Regular Appointment",
    ],
    times: ["9:00 AM", "10:30 AM", "1:00 PM", "3:30 PM"],
  },
  seo: {
    title: "Miriã Cotrim | Bridal Beauty, Hair & Makeup",
    description:
      "Premium bridal hair, makeup, special event beauty and personalized appointments with Miriã Cotrim in Orlando and Miami.",
  },
  copy: {
    eyebrow: "BRIDAL BEAUTY • HAIR • MAKEUP",
    hero: "Beauty for your",
    heroEm: "most beautiful",
    heroEnd: "moments.",
    heroSub:
      "Premium bridal hair, makeup and event beauty designed around your story, your style and the way you want to feel.",
    book: "Book an appointment",
    explore: "Explore bridal services",
    position: "Bridal beauty, elevated.",
    positionText:
      "More than a beautiful look. A feeling of being entirely yourself. Discover personalized hair and makeup for noivas, madrinhas, special events and unforgettable portraits.",
    portfolio: "The art of feeling beautiful.",
    about: "Meet Miriã",
    behind: "Behind the beauty",
    signature: "Signature looks",
    confirmation: "Your request was sent.",
    confirmationText:
      "Thank you. Miriã's team will review your message and follow up soon.",
    next: "Continue",
    back: "Back",
    submit: "Send booking request",
    clientLove: "Client love",
    testimonial: "Client testimonial will appear here.",
  },
};

export const portfolio = [
  [0, "Updos"],
  [27, "Brides"],
  [46, "Natural & Curly Hair"],
  [39, "Updos"],
  [21, "Waves & Curls"],
  [15, "Half-Up Styles"],
  [12, "Ponytails"],
  [53, "Updos"],
  [44, "Brides"],
  [35, "Half-Up Styles"],
  [19, "Updos"],
  [48, "Ponytails"],
  [13, "Half-Up Styles"],
  [16, "Half-Up Styles"],
  [17, "Half-Up Styles"],
  [18, "Waves & Curls"],
  [20, "Waves & Curls"],
  [23, "Half-Up Styles"],
  [24, "Waves & Curls"],
  [25, "Brides"],
  [26, "Brides"],
  [28, "Brides"],
  [29, "Half-Up Styles"],
  [33, "Half-Up Styles"],
  [34, "Half-Up Styles"],
  [36, "Half-Up Styles"],
  [37, "Half-Up Styles"],
  [38, "Updos"],
  [41, "Updos"],
  [42, "Updos"],
  [43, "Updos"],
  [45, "Updos"],
  [47, "Natural & Curly Hair"],
  [49, "Updos"],
  [50, "Half-Up Styles"],
  [51, "Waves & Curls"],
  [52, "Updos"],
].map(([id, category]) => ({ id: Number(id), category: String(category) }));

export const categories = [
  "All",
  "Brides",
  "Updos",
  "Half-Up Styles",
  "Waves & Curls",
  "Ponytails",
  "Natural & Curly Hair",
];

export const photo = (id: number, small = false) =>
  `/images/${String(id).padStart(2, "0")}${small ? "-sm" : ""}.webp`;

export const pageTitles: Record<string, string> = {
  about: "Beauty with a personal touch.",
  services: "For every beautiful moment.",
  bridal: "Your day. Uniquely you.",
  portfolio: "A collection of beautiful moments.",
  contact: "Let's create something beautiful.",
};
